INSERT INTO COLLECTION (ID, TITLE)
VALUES
    (1, 'Hats'),
    (2, 'Mens'),
    (3, 'Jackets'),
    (4, 'Womens'),
    (5, 'Sneakers');
INSERT INTO item (id, IMAGE_URL, NAME, PRICE,COLLECTION_ID)
VALUES
    (1, 'https://i.ibb.co/ZYW3VTp/brown-brim.png', 'Brown Brim', 25, 1),
    (2, 'https://i.ibb.co/ypkgK0X/blue-beanie.png', 'Blue Beanie', 18, 1),
    (3, 'https://i.ibb.co/QdJwgmp/brown-cowboy.png', 'Brown Cowboy', 35, 1),
    (4, 'https://i.ibb.co/RjBLWxB/grey-brim.png', 'Grey Brim', 25, 1),
    (5, 'https://i.ibb.co/YTjW3vF/green-beanie.png', 'Green Beanie', 18, 1),
    (30, 'https://i.ibb.co/xJS0T3Y/camo-vest.png', 'Camo Down Vest', 320, 2),
    (31, 'https://i.ibb.co/qMQ75QZ/floral-shirt.png', 'Floral T-shirt', 20, 2),
    (32, 'https://i.ibb.co/55z32tw/long-sleeve.png', 'Black & White Longsleeve', 25, 2),
    (33, 'https://i.ibb.co/RvwnBL8/pink-shirt.png', 'Pink T-shirt', 25, 2),
    (34, 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png', 'Jean Long Sleeve', 40, 2),
    (35, 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png', 'Burgundy T-shirt', 25, 2),
    (18, 'https://i.ibb.co/XzcwL5s/black-shearling.png', 'Black Jean Shearling', 125, 3),
    (19, 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png', 'Blue Jean Jacket', 90, 3),
    (20, 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png', 'Grey Jean Jacket', 90, 3),
    (21, 'https://i.ibb.co/s96FpdP/brown-shearling.png', 'Brown Shearling', 165, 3),
    (22, 'https://i.ibb.co/M6hHc3F/brown-trench.png', 'Tan Trench', 185, 3),
    (23, 'https://i.ibb.co/7CQVJNm/blue-tank.png', 'Blue Tanktop', 25, 4),
    (24, 'https://i.ibb.co/4W2DGKm/floral-blouse.png', 'Floral Blouse', 20, 4),
    (25, 'https://i.ibb.co/KV18Ysr/floral-skirt.png', 'Floral Dress', 80, 4),
    (26, 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png', 'Red Dots Dress', 80, 4),
    (27, 'https://i.ibb.co/KmSkMbH/striped-sweater.png', 'Striped Sweater', 45, 4),
    (10, 'https://i.ibb.co/0s3pdnc/adidas-nmd.png', 'Adidas NMD', 220, 5),
    (11, 'https://i.ibb.co/dJbG1cT/yeezy.png', 'Adidas Yeezy', 280, 5),
    (12, 'https://i.ibb.co/bPmVXyP/black-converse.png', 'Black Converse', 110, 5),
    (13, 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png', 'Nike White AirForce', 160, 5),
    (14, 'https://i.ibb.co/QcvzydB/nikes-red.png', 'Nike Red High Tops', 160, 5),
    (15, 'https://i.ibb.co/fMTV342/nike-brown.png', 'Nike Brown High Tops', 160, 5),
    (16, 'https://i.ibb.co/w4k6Ws9/nike-funky.png', 'Air Jordan Limited', 190, 5),
    (17, 'https://i.ibb.co/Mhh6wBg/timberlands.png', 'Timberlands', 200, 5);
